matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      language: cpp
      services:
        - docker
      script:
        - docker build -t hipo_tools . -f docker/Dockerfile.travis
        - docker images -a
    - os: osx
      language: cpp
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Cellar
          - /usr/local/Homebrew
      before_install:
        - brew install llvm; echo "Done"
        - brew install lz4; echo "Done"
        - brew install gcc; echo "Done"
        - brew install root; echo "Done"
        - pip install cython scikit-build numpy
      install:
        - mkdir build && cd build
        - CXX=/usr/local/opt/llvm/bin/clang++ CC=/usr/local/opt/llvm/bin/clang cmake .. -DCMAKE_INSTALL_PREFIX=install
        - make
        - make install
      script:
        - python -c 'from hipopy import hipo_reader;'
