matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      language: cpp
      services:
        - docker
      script:
        - docker build -t hipo_tools . -f docker/Dockerfile.travis
        - docker images -a
    - os: osx
      language: cpp
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Cellar
      script:
        - brew install llvm
        - brew install lz4
        - brew install gcc
        - brew install root
        - mkdir build && cd build
        - CXX=/usr/local/opt/llvm/bin/clang++ CC=/usr/local/opt/llvm/bin/clang cmake .. -DCMAKE_INSTALL_PREFIX=install
        - make
        - make install
