matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      language: cpp
      services:
        - docker
      script:
        - docker build -t hipo_tools . -f docker/Dockerfile.travis
        - docker images -a
    - os: osx
      language: cpp
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
      env:
        - CXX=/usr/local/opt/llvm/bin/clang++
        - CC=/usr/local/opt/llvm/bin/clang
      before_script:
        - brew install root llvm
      script:
        - cd hipo_tools
        - mkdir build && cd build
        - cmake .. -DCMAKE_INSTALL_PREFIX=install
        - make
        - make install
