#!/usr/bin/env python
from __future__ import print_function
import json
import pprint
import glob
import os
import argparse

# TODO: get the needed banks from config file
all_files = [
    "bankdefs/hipo/BST.json", "bankdefs/hipo/DC.json", "bankdefs/hipo/MC.json",
    "bankdefs/hipo/CND.json", "bankdefs/hipo/ECAL.json",
    "bankdefs/hipo/HTCC.json", "bankdefs/hipo/TOF.json",
    "bankdefs/hipo/HEADER.json", "bankdefs/hipo/DETECTOR.json",
    "bankdefs/hipo/FMT.json", "bankdefs/hipo/EVENT.json",
    "bankdefs/hipo/BMT.json", "bankdefs/hipo/CVT.json",
    "bankdefs/hipo/DATA.json", "bankdefs/hipo/FT.json",
    "bankdefs/hipo/LTCC.json"
]

clas6 = ["bankdefs/hipo/CLAS6EVENT.json"]

small = ["bankdefs/hipo/EVENT.json"]

root_check = {
    "int8": "int",
    "int16": "int",
    "int32": "int",
    "float": "float",
    "double": "float",
    "int64": "int",
    "vector3f": "float"
}

hipo_check = {
    "int8": "int8_t",
    "int16": "int16_t",
    "int32": "int32_t",
    "float": "float",
    "double": "float",
    "int64": "int64_t",
    "vector3f": "float"
}

middle = r"""
  int entry = 0;
  int l = 0;
  while (reader.next() == true) {
    entry++;
    if ((entry % 1000) == 0) std::cerr << "\t" << entry << "\r\r" << std::flush;
"""
# loop = """
#    %s = event.get%s(%s, %s);"""

loop = r"""
    l = %s->getLength();
    %s.resize(l);
    for (int i = 0; i < l; i++) %s.at(i) = %s->getValue(i);

    """

ending = r"""
  }
  OutputFile->cd();
  clas12->Write();
  OutputFile->Close();

  return 0;
}
"""
begining = r"""/*
* This code was auto generated by make_hipo2root.py
* Do not modify this program.
*
*
*
* Author: Nick Tyler, University Of South Carolina
*/
// Standard libs
#include <cstdlib>
#include <iostream>
#include <time.h>
#include <vector>
// ROOT libs
#include "TFile.h"
#include "TTree.h"
// Hipo libs
#include "hipo/reader.h"

int main(int argc, char **argv) {

  char InFileName[128];
  char OutFileName[128];

  if (argc == 2) {
    sprintf(InFileName, "%s", argv[1]);
    sprintf(OutFileName, "%s.root", argv[1]);
    std::cout << OutFileName << std::endl;
  } else if (argc == 3) {
    sprintf(InFileName, "%s", argv[1]);
    sprintf(OutFileName, "%s", argv[2]);
  } else {
    std::cout << "Please provide a filename to read...." << std::endl;
    exit(0);
  }
    TFile *OutputFile = new TFile(OutFileName, "RECREATE");
    OutputFile->SetCompressionSettings(9);
    TTree *clas12 = new TTree("clas12", "clas12");
  hipo::reader reader;
  reader.open(InFileName);
"""

node = r"""
hipo::node<%s> *%s_node = reader.getBranch<%s>(%s, %s);"""


def make_hipo2root(files):
    root_branches = []
    root_vectors = []
    loops = []
    clear_vec = []
    hipo_nodes = []
    for filename in files:
        with open(filename) as data_file:
            data = json.load(data_file)
            for bank in data:
                bank_name = str(bank["bank"])
                group = str(bank["group"])
                info = str(bank["info"])
                items = bank["items"]
                for item in items:
                    root_type = root_check[str(item["type"])]
                    hipo_type = hipo_check[str(item["type"])]
                    name = bank_name.replace("::", "_") + "_" + str(
                        item["name"])
                    loops.append(loop % (name + "_node", name + "_vec",
                                         name + "_vec", name + "_node"))
                    root_vectors.append("\tstd::vector<" + root_type + "> " +
                                        name + "_vec; \n")
                    root_branches.append("\t" + "clas12->Branch(\"" + name +
                                         "\",&" + name + "_vec); \n")

                    hipo_nodes.append(node % (hipo_type, name, hipo_type,
                                              group, str(item["id"])))

                    clear_vec.append("\t\t" + name + "_vec.clear();  \n")

    with open("recon2root.cpp", 'w') as outfile:
        def write(x): return outfile.write(x)
        write(begining)
        write("\n\n")
        map(write, hipo_nodes)
        write("\n\n")
        map(write, root_vectors)
        write("\n\n")
        map(write, root_branches)
        map(write, middle)
        map(write, loops)
        write("\n\t\tclas12->Fill();\n")
        map(write, clear_vec)
        write(ending)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Make cpp file for converting hipo to root format')
    parser.add_argument(
        '-a',
        '--ALL',
        action='store_true',
        help='Add all banks from bankdefs/hipo/*.json, overrides all other options')
    parser.add_argument(
        '--json',
        nargs='+',
        help='Specify json file/files for bank information, overrides all other options'
    )
    parser.add_argument(
        '--clas6', action='store_true', help="Add banks from clas6")
    parser.add_argument('--BST', action='store_true', help='Add bank BST')
    parser.add_argument('--DC', action='store_true', help='Add bank DC')
    parser.add_argument('--MC', action='store_true', help='Add bank MC')
    parser.add_argument('--CND', action='store_true', help='Add bank CND')
    parser.add_argument('--ECAL', action='store_true', help='Add bank ECAL')
    parser.add_argument('--HTCC', action='store_true', help='Add bank HTCC')
    parser.add_argument('--TOF', action='store_true', help='Add bank TOF')
    parser.add_argument(
        '--HEADER', action='store_true', help='Add bank HEADER')
    parser.add_argument(
        '--DETECTOR', action='store_true', help='Add bank DETECTOR')
    parser.add_argument('--FMT', action='store_true', help='Add bank FMT')
    parser.add_argument('--EVENT', action='store_true', help='Add bank EVENT')
    parser.add_argument('--BMT', action='store_true', help='Add bank BMT')
    parser.add_argument('--CVT', action='store_true', help='Add bank CVT')
    parser.add_argument('--DATA', action='store_true', help='Add bank DATA')
    parser.add_argument('--FT', action='store_true', help='Add bank FT')
    parser.add_argument('--LTCC', action='store_true', help='Add bank LTCC')

    args = parser.parse_args()
    files = []
    if (args.ALL):
        files = all_files
    elif (args.json):
        files = args.json
    else:
        for arg in vars(args):
            if arg is not 'ALL' and arg is not 'json':
                if getattr(args, arg):
                    files.append('bankdefs/hipo/' + str(arg) + '.json')
    if len(files) == 0:
        files = small
    # print(files)
    make_hipo2root(files)
